In [4]:
import pandas as pd
PATH = '../corpus/4_tokens/tokens6_18_score.tsv'
df = pd.read_csv(PATH, encoding = 'utf-8', sep = '\t')
df[10:30]

,Unnamed: 0,Unnamed: 0.1,age,tokens,selected_tokens,senti_words,senti_score
10,10,10,6,그리고 다 치우 고 1 분 도 안 대 서 완성 을 했 다 .,그리고 다 치우 분 안 대 완성 했,"[('분', -2), ('대', 0)]",-1.0
11,11,11,6,진짜 가습기 연한 을 하 는지 궁 군 했 는대 . 엄마 가 완성 한 걸 버려 다 .,진짜 가습기 연한 하 궁 군 했 엄마 완성 한 걸 버려 다,"[('하', 1), ('완성', 1)]",1.0
12,12,12,6,그래서 조금 아 시 워다 .,그래서 조금 시 워 다,None,None
13,13,13,6,그래도 참 재미 섰 다 .,그래도 참 재미 섰,"[('참', -1)]",-1.0
14,14,14,6,다음 엔 더 만 이 만들 고 십 다 .,다음 엔 더 만 이 만들 십 다,None,None
15,15,15,6,그리고 방 이 깩 그댄 저서 기분 이 만 이 만 이 좋 았 다 .,그리고 방 이 깩 그댄 저서 기분 이 만 이 만 이 좋,"[('좋', 2)]",2.0
16,16,16,6,다음 에 는 겨울 에서 배운 겄 도 했 보 고 십 다 .,다음 에 겨울 배운 겄 했 보 십 다,"[('보', -1)]",-1.0
17,17,17,6,2 학년 땐 겨울 에서 배운 겄 을 만들 어 보 고 십 다 .,학년 땐 겨울 배운 겄 만들 보 십 다,"[('보', -1)]",-1.0
18,18,18,6,가족 과 이화동 벽화 마을 에 있 는 옛날 교복 을 입 으려고 갔 다 . 가선 교복...,가족 과 이화동 벽화 마을 있 옛날 교복 입 갔 가선 교복 입 모자 썼,"[('모자', -1)]",-1.0
19,19,19,6,거울 을 봐 보 니 정말 예 뻣 다 .,거울 봐 보 정말 뻣 다,"[('보', -1)]",-1.0
20,20,20,6,바람개비 삔 을 사 서 모지 에 꽂 았 다 .,바람개비 삔 을 사 모지 꽂,None,None
21,21,21,6,뛰 어 보 니 아주 잘 돌 아 갔 다 .,뛰 보 아주 잘 돌 갔,"[('보', -1), ('잘', 1)]",0.0
22,22,22,6,신사 아저씨 와 강아지 를 보 면서 사진 을 찍 고 계단 에서 도 사진 을 찍 었 다 .,신사 아저씨 와 강아지 보 사진 찍 계단 도 사진 찍,"[('보', -1)]",-1.0
23,23,23,6,벽 에 드 그림 이 많 아서 찍 었 다 .,벽 드 그림 이 많 찍,"[('많', 2)]",2.0
24,24,24,6,이제 교복 을 돌려주 었 다 .,이제 교복 돌려주,None,None
25,25,25,6,나 도 빨리 커서 교복 을 입 어 보 고 학교 에 도 가 고 싶 다 .,나 빨리 커서 교복 입 보 학교 도 가 싶,"[('보', -1)]",-1.0
26,26,26,6,왜냐면 교복 이 너무 예뻤 기 때문 이 다 .,왜냐면 교복 이 너무 예뻤 때문 이,None,None
27,27,27,6,"나 는 오후 에 학교 , 학원 을 마치 고 놀이터 에서 친구 , 오빠 , 언니 들 ...",나 오후 학교 학원 마치 놀이터 친구 오빠 언니 들 이랑 뱀파이어 와 악수 라는 놀이 했,"[('친구', 1)]",1.0
28,28,28,6,나 는 뒤돌 아 있 을 때 갑자기 쉬 가 마려웠 다 .,나 뒤돌 있 때 갑자기 쉬 가 마려웠,"[('때', -1), ('쉬', -2)]",-1.5
29,29,29,6,하지만 놀이 가 너무 재미있 어서 집 에 가 기 싫 었 다 .,하지만 놀이 너무 재미있 집 가 싫,"[('재미있', 2), ('싫', -2)]",0.0

In [6]:
df['age'].value_counts().sort_index()

6     1086
7     3715
8     4591
9     4799
10    3490
11    2744
12    2016
13     986
14    3541
15    3433
16    6138
17    5739
18    7304
Name: age, dtype: int64

In [7]:
# label 생성
# 6~11세 : 0, 12~18세 : 1
df['label'] = [0 if s <11 else 1 for s in df['age']]
df[10:30]

,Unnamed: 0,Unnamed: 0.1,age,tokens,selected_tokens,senti_words,senti_score,label
10,10,10,6,그리고 다 치우 고 1 분 도 안 대 서 완성 을 했 다 .,그리고 다 치우 분 안 대 완성 했,"[('분', -2), ('대', 0)]",-1.0,0
11,11,11,6,진짜 가습기 연한 을 하 는지 궁 군 했 는대 . 엄마 가 완성 한 걸 버려 다 .,진짜 가습기 연한 하 궁 군 했 엄마 완성 한 걸 버려 다,"[('하', 1), ('완성', 1)]",1.0,0
12,12,12,6,그래서 조금 아 시 워다 .,그래서 조금 시 워 다,None,None,0
13,13,13,6,그래도 참 재미 섰 다 .,그래도 참 재미 섰,"[('참', -1)]",-1.0,0
14,14,14,6,다음 엔 더 만 이 만들 고 십 다 .,다음 엔 더 만 이 만들 십 다,None,None,0
15,15,15,6,그리고 방 이 깩 그댄 저서 기분 이 만 이 만 이 좋 았 다 .,그리고 방 이 깩 그댄 저서 기분 이 만 이 만 이 좋,"[('좋', 2)]",2.0,0
16,16,16,6,다음 에 는 겨울 에서 배운 겄 도 했 보 고 십 다 .,다음 에 겨울 배운 겄 했 보 십 다,"[('보', -1)]",-1.0,0
17,17,17,6,2 학년 땐 겨울 에서 배운 겄 을 만들 어 보 고 십 다 .,학년 땐 겨울 배운 겄 만들 보 십 다,"[('보', -1)]",-1.0,0
18,18,18,6,가족 과 이화동 벽화 마을 에 있 는 옛날 교복 을 입 으려고 갔 다 . 가선 교복...,가족 과 이화동 벽화 마을 있 옛날 교복 입 갔 가선 교복 입 모자 썼,"[('모자', -1)]",-1.0,0
19,19,19,6,거울 을 봐 보 니 정말 예 뻣 다 .,거울 봐 보 정말 뻣 다,"[('보', -1)]",-1.0,0
20,20,20,6,바람개비 삔 을 사 서 모지 에 꽂 았 다 .,바람개비 삔 을 사 모지 꽂,None,None,0
21,21,21,6,뛰 어 보 니 아주 잘 돌 아 갔 다 .,뛰 보 아주 잘 돌 갔,"[('보', -1), ('잘', 1)]",0.0,0
22,22,22,6,신사 아저씨 와 강아지 를 보 면서 사진 을 찍 고 계단 에서 도 사진 을 찍 었 다 .,신사 아저씨 와 강아지 보 사진 찍 계단 도 사진 찍,"[('보', -1)]",-1.0,0
23,23,23,6,벽 에 드 그림 이 많 아서 찍 었 다 .,벽 드 그림 이 많 찍,"[('많', 2)]",2.0,0
24,24,24,6,이제 교복 을 돌려주 었 다 .,이제 교복 돌려주,None,None,0
25,25,25,6,나 도 빨리 커서 교복 을 입 어 보 고 학교 에 도 가 고 싶 다 .,나 빨리 커서 교복 입 보 학교 도 가 싶,"[('보', -1)]",-1.0,0
26,26,26,6,왜냐면 교복 이 너무 예뻤 기 때문 이 다 .,왜냐면 교복 이 너무 예뻤 때문 이,None,None,0
27,27,27,6,"나 는 오후 에 학교 , 학원 을 마치 고 놀이터 에서 친구 , 오빠 , 언니 들 ...",나 오후 학교 학원 마치 놀이터 친구 오빠 언니 들 이랑 뱀파이어 와 악수 라는 놀이 했,"[('친구', 1)]",1.0,0
28,28,28,6,나 는 뒤돌 아 있 을 때 갑자기 쉬 가 마려웠 다 .,나 뒤돌 있 때 갑자기 쉬 가 마려웠,"[('때', -1), ('쉬', -2)]",-1.5,0
29,29,29,6,하지만 놀이 가 너무 재미있 어서 집 에 가 기 싫 었 다 .,하지만 놀이 너무 재미있 집 가 싫,"[('재미있', 2), ('싫', -2)]",0.0,0

In [8]:
df2 = df.replace({'senti_score':'None'},0)
df2[10:30]

,Unnamed: 0,Unnamed: 0.1,age,tokens,selected_tokens,senti_words,senti_score,label
10,10,10,6,그리고 다 치우 고 1 분 도 안 대 서 완성 을 했 다 .,그리고 다 치우 분 안 대 완성 했,"[('분', -2), ('대', 0)]",-1.0,0
11,11,11,6,진짜 가습기 연한 을 하 는지 궁 군 했 는대 . 엄마 가 완성 한 걸 버려 다 .,진짜 가습기 연한 하 궁 군 했 엄마 완성 한 걸 버려 다,"[('하', 1), ('완성', 1)]",1.0,0
12,12,12,6,그래서 조금 아 시 워다 .,그래서 조금 시 워 다,None,0,0
13,13,13,6,그래도 참 재미 섰 다 .,그래도 참 재미 섰,"[('참', -1)]",-1.0,0
14,14,14,6,다음 엔 더 만 이 만들 고 십 다 .,다음 엔 더 만 이 만들 십 다,None,0,0
15,15,15,6,그리고 방 이 깩 그댄 저서 기분 이 만 이 만 이 좋 았 다 .,그리고 방 이 깩 그댄 저서 기분 이 만 이 만 이 좋,"[('좋', 2)]",2.0,0
16,16,16,6,다음 에 는 겨울 에서 배운 겄 도 했 보 고 십 다 .,다음 에 겨울 배운 겄 했 보 십 다,"[('보', -1)]",-1.0,0
17,17,17,6,2 학년 땐 겨울 에서 배운 겄 을 만들 어 보 고 십 다 .,학년 땐 겨울 배운 겄 만들 보 십 다,"[('보', -1)]",-1.0,0
18,18,18,6,가족 과 이화동 벽화 마을 에 있 는 옛날 교복 을 입 으려고 갔 다 . 가선 교복...,가족 과 이화동 벽화 마을 있 옛날 교복 입 갔 가선 교복 입 모자 썼,"[('모자', -1)]",-1.0,0
19,19,19,6,거울 을 봐 보 니 정말 예 뻣 다 .,거울 봐 보 정말 뻣 다,"[('보', -1)]",-1.0,0
20,20,20,6,바람개비 삔 을 사 서 모지 에 꽂 았 다 .,바람개비 삔 을 사 모지 꽂,None,0,0
21,21,21,6,뛰 어 보 니 아주 잘 돌 아 갔 다 .,뛰 보 아주 잘 돌 갔,"[('보', -1), ('잘', 1)]",0.0,0
22,22,22,6,신사 아저씨 와 강아지 를 보 면서 사진 을 찍 고 계단 에서 도 사진 을 찍 었 다 .,신사 아저씨 와 강아지 보 사진 찍 계단 도 사진 찍,"[('보', -1)]",-1.0,0
23,23,23,6,벽 에 드 그림 이 많 아서 찍 었 다 .,벽 드 그림 이 많 찍,"[('많', 2)]",2.0,0
24,24,24,6,이제 교복 을 돌려주 었 다 .,이제 교복 돌려주,None,0,0
25,25,25,6,나 도 빨리 커서 교복 을 입 어 보 고 학교 에 도 가 고 싶 다 .,나 빨리 커서 교복 입 보 학교 도 가 싶,"[('보', -1)]",-1.0,0
26,26,26,6,왜냐면 교복 이 너무 예뻤 기 때문 이 다 .,왜냐면 교복 이 너무 예뻤 때문 이,None,0,0
27,27,27,6,"나 는 오후 에 학교 , 학원 을 마치 고 놀이터 에서 친구 , 오빠 , 언니 들 ...",나 오후 학교 학원 마치 놀이터 친구 오빠 언니 들 이랑 뱀파이어 와 악수 라는 놀이 했,"[('친구', 1)]",1.0,0
28,28,28,6,나 는 뒤돌 아 있 을 때 갑자기 쉬 가 마려웠 다 .,나 뒤돌 있 때 갑자기 쉬 가 마려웠,"[('때', -1), ('쉬', -2)]",-1.5,0
29,29,29,6,하지만 놀이 가 너무 재미있 어서 집 에 가 기 싫 었 다 .,하지만 놀이 너무 재미있 집 가 싫,"[('재미있', 2), ('싫', -2)]",0.0,0

In [9]:
df2.dtypes

Unnamed: 0          int64
Unnamed: 0.1        int64
age                 int64
tokens             object
selected_tokens    object
senti_words        object
senti_score        object
label               int64
dtype: object

In [10]:
df2['senti_score']  = pd.to_numeric(df2["senti_score"])
df2[10:30]

,Unnamed: 0,Unnamed: 0.1,age,tokens,selected_tokens,senti_words,senti_score,label
10,10,10,6,그리고 다 치우 고 1 분 도 안 대 서 완성 을 했 다 .,그리고 다 치우 분 안 대 완성 했,"[('분', -2), ('대', 0)]",-1.0,0
11,11,11,6,진짜 가습기 연한 을 하 는지 궁 군 했 는대 . 엄마 가 완성 한 걸 버려 다 .,진짜 가습기 연한 하 궁 군 했 엄마 완성 한 걸 버려 다,"[('하', 1), ('완성', 1)]",1.0,0
12,12,12,6,그래서 조금 아 시 워다 .,그래서 조금 시 워 다,None,0.0,0
13,13,13,6,그래도 참 재미 섰 다 .,그래도 참 재미 섰,"[('참', -1)]",-1.0,0
14,14,14,6,다음 엔 더 만 이 만들 고 십 다 .,다음 엔 더 만 이 만들 십 다,None,0.0,0
15,15,15,6,그리고 방 이 깩 그댄 저서 기분 이 만 이 만 이 좋 았 다 .,그리고 방 이 깩 그댄 저서 기분 이 만 이 만 이 좋,"[('좋', 2)]",2.0,0
16,16,16,6,다음 에 는 겨울 에서 배운 겄 도 했 보 고 십 다 .,다음 에 겨울 배운 겄 했 보 십 다,"[('보', -1)]",-1.0,0
17,17,17,6,2 학년 땐 겨울 에서 배운 겄 을 만들 어 보 고 십 다 .,학년 땐 겨울 배운 겄 만들 보 십 다,"[('보', -1)]",-1.0,0
18,18,18,6,가족 과 이화동 벽화 마을 에 있 는 옛날 교복 을 입 으려고 갔 다 . 가선 교복...,가족 과 이화동 벽화 마을 있 옛날 교복 입 갔 가선 교복 입 모자 썼,"[('모자', -1)]",-1.0,0
19,19,19,6,거울 을 봐 보 니 정말 예 뻣 다 .,거울 봐 보 정말 뻣 다,"[('보', -1)]",-1.0,0
20,20,20,6,바람개비 삔 을 사 서 모지 에 꽂 았 다 .,바람개비 삔 을 사 모지 꽂,None,0.0,0
21,21,21,6,뛰 어 보 니 아주 잘 돌 아 갔 다 .,뛰 보 아주 잘 돌 갔,"[('보', -1), ('잘', 1)]",0.0,0
22,22,22,6,신사 아저씨 와 강아지 를 보 면서 사진 을 찍 고 계단 에서 도 사진 을 찍 었 다 .,신사 아저씨 와 강아지 보 사진 찍 계단 도 사진 찍,"[('보', -1)]",-1.0,0
23,23,23,6,벽 에 드 그림 이 많 아서 찍 었 다 .,벽 드 그림 이 많 찍,"[('많', 2)]",2.0,0
24,24,24,6,이제 교복 을 돌려주 었 다 .,이제 교복 돌려주,None,0.0,0
25,25,25,6,나 도 빨리 커서 교복 을 입 어 보 고 학교 에 도 가 고 싶 다 .,나 빨리 커서 교복 입 보 학교 도 가 싶,"[('보', -1)]",-1.0,0
26,26,26,6,왜냐면 교복 이 너무 예뻤 기 때문 이 다 .,왜냐면 교복 이 너무 예뻤 때문 이,None,0.0,0
27,27,27,6,"나 는 오후 에 학교 , 학원 을 마치 고 놀이터 에서 친구 , 오빠 , 언니 들 ...",나 오후 학교 학원 마치 놀이터 친구 오빠 언니 들 이랑 뱀파이어 와 악수 라는 놀이 했,"[('친구', 1)]",1.0,0
28,28,28,6,나 는 뒤돌 아 있 을 때 갑자기 쉬 가 마려웠 다 .,나 뒤돌 있 때 갑자기 쉬 가 마려웠,"[('때', -1), ('쉬', -2)]",-1.5,0
29,29,29,6,하지만 놀이 가 너무 재미있 어서 집 에 가 기 싫 었 다 .,하지만 놀이 너무 재미있 집 가 싫,"[('재미있', 2), ('싫', -2)]",0.0,0

In [11]:
df2.groupby(['label'], as_index=False).mean()

   label  Unnamed: 0  Unnamed: 0.1        age  senti_score
0      0      8840.0        8840.0   8.333239     0.088991
1      1     33631.0       33631.0  15.532617    -0.066327

In [12]:
df2.groupby(['label'], as_index=False).std()

   label   Unnamed: 0  Unnamed: 0.1       age  senti_score
0      0  5104.209390   5104.209390  1.185665     1.006914
1      1  9209.169805   9209.169805  2.206526     1.001923

In [13]:
df2.groupby(['age'], as_index=False).mean()

    age  Unnamed: 0  Unnamed: 0.1  senti_score  label
0     6       542.5         542.5     0.070530    0.0
1     7      2943.0        2943.0     0.123346    0.0
2     8      7096.0        7096.0     0.127610    0.0
3     9     11791.0       11791.0     0.064958    0.0
4    10     15935.5       15935.5     0.040411    0.0
5    11     19052.5       19052.5     0.007229    1.0
6    12     21432.5       21432.5    -0.014009    1.0
7    13     22933.5       22933.5     0.008672    1.0
8    14     25197.0       25197.0    -0.040231    1.0
9    15     28684.0       28684.0    -0.088574    1.0
10   16     33469.5       33469.5    -0.073207    1.0
11   17     39408.0       39408.0    -0.104496    1.0
12   18     45929.5       45929.5    -0.084947    1.0

In [14]:
# t-test
from scipy.stats import levene
young = df2['senti_score'][(df2.label == 0)]
old = df2['senti_score'][(df2.label == 1)]
levene(young, old) # Homogeneity of Variance Test

LeveneResult(statistic=44.08354538173264, pvalue=3.17891454012575e-11)

In [15]:
# Welche's t-test
from scipy import stats
stats.ttest_ind(young, old, equal_var=False)

Ttest_indResult(statistic=16.481202029709074, pvalue=8.329220944252694e-61)